import { RIMA_BASEMAP_LAYER_ID, RIMA_MAPVIEW_BASEMAP_WMTS_URL } from '../../map-config';

export { RIMA_MAPVIEW_BASEMAP_WMTS_URL };

// BASEMAP
export const RIMA_MAPVIEW_BASEMAP_LAYER_ID = RIMA_BASEMAP_LAYER_ID;

// LAYER FILTERING
export const RIMA_MAPVIEW_WRAP_WEBMAP_AS_GROUP = true;
export const RIMA_MAPVIEW_HIDDEN_CATEGORY = 'HIDDEN';
